//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DeptwiseDoctor
    {
        public int DeptwiseId { get; set; }
        public int DepartmentId { get; set; }
        public int DoctorId { get; set; }
        [Required]
        public string Designation { get; set; }
        [Required]
        public string Institution { get; set; }
        [Display(Name ="Visit Fee")]
        public decimal VisitFee { get; set; }
        public string Picture { get; set; }
    
        public virtual Departments_ Departments_ { get; set; }
        public virtual Doctors_ Doctors_ { get; set; }
    }
}
