//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Doctors_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctors_()
        {
            this.DeptwiseDoctors = new HashSet<DeptwiseDoctor>();
            this.Doctors_Salary = new HashSet<Doctors_Salary>();
        }
    
        public int DoctorId { get; set; }
        [Display(Name="Doctor Name")]
        public string Name { get; set; }
        public Nullable<int> PatientId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeptwiseDoctor> DeptwiseDoctors { get; set; }
        public virtual Doctors_ Doctors_1 { get; set; }
        public virtual Doctors_ Doctors_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctors_Salary> Doctors_Salary { get; set; }
        public virtual Patinet Patinet { get; set; }
    }
}
