//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Maintenence_Employee
    {
        public int EmpId { get; set; }
        [Display(Name ="Emp Name")]
        public string Name { get; set; }
        [Required]
        public Nullable<int> Phone { get; set; }
        [Display(Name="work-section")]
        public string Work_section { get; set; }
        public decimal Salary { get; set; }
        [Display(Name="Admin-Role")]
        public Nullable<int> AdminId { get; set; }
    
        public virtual AdminPanel AdminPanel { get; set; }
    }
}
