//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hosmsEntities : DbContext
    {
        public hosmsEntities()
            : base("name=hosmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminPanel> AdminPanels { get; set; }
        public virtual DbSet<Departments_> Departments_ { get; set; }
        public virtual DbSet<DeptwiseDoctor> DeptwiseDoctors { get; set; }
        public virtual DbSet<Doctors_> Doctors_ { get; set; }
        public virtual DbSet<Doctors_Salary> Doctors_Salaries { get; set; }
        public virtual DbSet<Maintenence_Employee> Maintenence_Employees { get; set; }
        public virtual DbSet<Nurse> Nurses { get; set; }
        public virtual DbSet<Patinet> Patinets { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    }
}
